# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Accounts do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Accounts"
  ]

  @type t :: %__MODULE__{
    :"Accounts" => [XeroAccountingAPI.Model.Account.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Accounts do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Accounts", :list, XeroAccountingAPI.Model.Account, options)
  end
end

