# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Actions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Actions"
  ]

  @type t :: %__MODULE__{
    :"Actions" => [XeroAccountingAPI.Model.Action.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Actions do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Actions", :list, XeroAccountingAPI.Model.Action, options)
  end
end

