# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Allocation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Invoice",
    :"Overpayment",
    :"Prepayment",
    :"CreditNote",
    :"Amount",
    :"Date",
    :"StatusAttributeString",
    :"ValidationErrors"
  ]

  @type t :: %__MODULE__{
    :"Invoice" => XeroAccountingAPI.Model.Invoice.t,
    :"Overpayment" => XeroAccountingAPI.Model.Overpayment.t | nil,
    :"Prepayment" => XeroAccountingAPI.Model.Prepayment.t | nil,
    :"CreditNote" => XeroAccountingAPI.Model.CreditNote.t | nil,
    :"Amount" => float(),
    :"Date" => String.t,
    :"StatusAttributeString" => String.t | nil,
    :"ValidationErrors" => [XeroAccountingAPI.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Allocation do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Invoice", :struct, XeroAccountingAPI.Model.Invoice, options)
    |> deserialize(:"Overpayment", :struct, XeroAccountingAPI.Model.Overpayment, options)
    |> deserialize(:"Prepayment", :struct, XeroAccountingAPI.Model.Prepayment, options)
    |> deserialize(:"CreditNote", :struct, XeroAccountingAPI.Model.CreditNote, options)
    |> deserialize(:"ValidationErrors", :list, XeroAccountingAPI.Model.ValidationError, options)
  end
end

