# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Allocations do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Allocations"
  ]

  @type t :: %__MODULE__{
    :"Allocations" => [XeroAccountingAPI.Model.Allocation.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Allocations do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Allocations", :list, XeroAccountingAPI.Model.Allocation, options)
  end
end

