# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Balances do
  @moduledoc """
  The raw AccountsReceivable(sales invoices) and AccountsPayable(bills) outstanding and overdue amounts, not converted to base currency (read only)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"AccountsReceivable",
    :"AccountsPayable"
  ]

  @type t :: %__MODULE__{
    :"AccountsReceivable" => XeroAccountingAPI.Model.AccountsReceivable.t | nil,
    :"AccountsPayable" => XeroAccountingAPI.Model.AccountsPayable.t | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Balances do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"AccountsReceivable", :struct, XeroAccountingAPI.Model.AccountsReceivable, options)
    |> deserialize(:"AccountsPayable", :struct, XeroAccountingAPI.Model.AccountsPayable, options)
  end
end

