# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.BankTransactions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"BankTransactions"
  ]

  @type t :: %__MODULE__{
    :"BankTransactions" => [XeroAccountingAPI.Model.BankTransaction.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.BankTransactions do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"BankTransactions", :list, XeroAccountingAPI.Model.BankTransaction, options)
  end
end

