# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.BatchPayments do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"BatchPayments"
  ]

  @type t :: %__MODULE__{
    :"BatchPayments" => [XeroAccountingAPI.Model.BatchPayment.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.BatchPayments do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"BatchPayments", :list, XeroAccountingAPI.Model.BatchPayment, options)
  end
end

