# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.BrandingThemes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"BrandingThemes"
  ]

  @type t :: %__MODULE__{
    :"BrandingThemes" => [XeroAccountingAPI.Model.BrandingTheme.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.BrandingThemes do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"BrandingThemes", :list, XeroAccountingAPI.Model.BrandingTheme, options)
  end
end

