# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Budget do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"BudgetID",
    :"Type",
    :"Description",
    :"UpdatedDateUTC",
    :"BudgetLines",
    :"Tracking"
  ]

  @type t :: %__MODULE__{
    :"BudgetID" => String.t | nil,
    :"Type" => String.t | nil,
    :"Description" => String.t | nil,
    :"UpdatedDateUTC" => String.t | nil,
    :"BudgetLines" => [XeroAccountingAPI.Model.BudgetLine.t] | nil,
    :"Tracking" => [XeroAccountingAPI.Model.TrackingCategory.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Budget do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"BudgetLines", :list, XeroAccountingAPI.Model.BudgetLine, options)
    |> deserialize(:"Tracking", :list, XeroAccountingAPI.Model.TrackingCategory, options)
  end
end

