# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Budgets do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Budgets"
  ]

  @type t :: %__MODULE__{
    :"Budgets" => [XeroAccountingAPI.Model.Budget.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Budgets do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Budgets", :list, XeroAccountingAPI.Model.Budget, options)
  end
end

