# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.CisSettings do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"CISSettings"
  ]

  @type t :: %__MODULE__{
    :"CISSettings" => [XeroAccountingAPI.Model.CisSetting.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.CisSettings do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"CISSettings", :list, XeroAccountingAPI.Model.CisSetting, options)
  end
end

