# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.ContactGroups do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ContactGroups"
  ]

  @type t :: %__MODULE__{
    :"ContactGroups" => [XeroAccountingAPI.Model.ContactGroup.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.ContactGroups do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ContactGroups", :list, XeroAccountingAPI.Model.ContactGroup, options)
  end
end

