# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Contacts do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Contacts"
  ]

  @type t :: %__MODULE__{
    :"Contacts" => [XeroAccountingAPI.Model.Contact.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Contacts do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Contacts", :list, XeroAccountingAPI.Model.Contact, options)
  end
end

