# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.ConversionBalances do
  @moduledoc """
  Balance supplied for each account that has a value as at the conversion date.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"AccountCode",
    :"Balance",
    :"BalanceDetails"
  ]

  @type t :: %__MODULE__{
    :"AccountCode" => String.t | nil,
    :"Balance" => float() | nil,
    :"BalanceDetails" => [XeroAccountingAPI.Model.BalanceDetails.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.ConversionBalances do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"BalanceDetails", :list, XeroAccountingAPI.Model.BalanceDetails, options)
  end
end

