# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.ConversionDate do
  @moduledoc """
  The date when the organisation starts using Xero
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Month",
    :"Year"
  ]

  @type t :: %__MODULE__{
    :"Month" => integer() | nil,
    :"Year" => integer() | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.ConversionDate do
  def decode(value, _options) do
    value
  end
end

