# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.CreditNotes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"CreditNotes"
  ]

  @type t :: %__MODULE__{
    :"CreditNotes" => [XeroAccountingAPI.Model.CreditNote.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.CreditNotes do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"CreditNotes", :list, XeroAccountingAPI.Model.CreditNote, options)
  end
end

