# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.CreditNote do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Type",
    :"Contact",
    :"Date",
    :"DueDate",
    :"Status",
    :"LineAmountTypes",
    :"LineItems",
    :"SubTotal",
    :"TotalTax",
    :"Total",
    :"CISDeduction",
    :"CISRate",
    :"UpdatedDateUTC",
    :"CurrencyCode",
    :"FullyPaidOnDate",
    :"CreditNoteID",
    :"CreditNoteNumber",
    :"Reference",
    :"SentToContact",
    :"CurrencyRate",
    :"RemainingCredit",
    :"Allocations",
    :"AppliedAmount",
    :"Payments",
    :"BrandingThemeID",
    :"StatusAttributeString",
    :"HasAttachments",
    :"HasErrors",
    :"ValidationErrors",
    :"Warnings"
  ]

  @type t :: %__MODULE__{
    :"Type" => String.t | nil,
    :"Contact" => XeroAccountingAPI.Model.Contact.t | nil,
    :"Date" => String.t | nil,
    :"DueDate" => String.t | nil,
    :"Status" => String.t | nil,
    :"LineAmountTypes" => XeroAccountingAPI.Model.LineAmountTypes.t | nil,
    :"LineItems" => [XeroAccountingAPI.Model.LineItem.t] | nil,
    :"SubTotal" => float() | nil,
    :"TotalTax" => float() | nil,
    :"Total" => float() | nil,
    :"CISDeduction" => float() | nil,
    :"CISRate" => float() | nil,
    :"UpdatedDateUTC" => String.t | nil,
    :"CurrencyCode" => XeroAccountingAPI.Model.CurrencyCode.t | nil,
    :"FullyPaidOnDate" => String.t | nil,
    :"CreditNoteID" => String.t | nil,
    :"CreditNoteNumber" => String.t | nil,
    :"Reference" => String.t | nil,
    :"SentToContact" => boolean() | nil,
    :"CurrencyRate" => float() | nil,
    :"RemainingCredit" => float() | nil,
    :"Allocations" => [XeroAccountingAPI.Model.Allocation.t] | nil,
    :"AppliedAmount" => float() | nil,
    :"Payments" => [XeroAccountingAPI.Model.Payment.t] | nil,
    :"BrandingThemeID" => String.t | nil,
    :"StatusAttributeString" => String.t | nil,
    :"HasAttachments" => boolean() | nil,
    :"HasErrors" => boolean() | nil,
    :"ValidationErrors" => [XeroAccountingAPI.Model.ValidationError.t] | nil,
    :"Warnings" => [XeroAccountingAPI.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.CreditNote do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Contact", :struct, XeroAccountingAPI.Model.Contact, options)
    |> deserialize(:"LineAmountTypes", :struct, XeroAccountingAPI.Model.LineAmountTypes, options)
    |> deserialize(:"LineItems", :list, XeroAccountingAPI.Model.LineItem, options)
    |> deserialize(:"CurrencyCode", :struct, XeroAccountingAPI.Model.CurrencyCode, options)
    |> deserialize(:"Allocations", :list, XeroAccountingAPI.Model.Allocation, options)
    |> deserialize(:"Payments", :list, XeroAccountingAPI.Model.Payment, options)
    |> deserialize(:"ValidationErrors", :list, XeroAccountingAPI.Model.ValidationError, options)
    |> deserialize(:"Warnings", :list, XeroAccountingAPI.Model.ValidationError, options)
  end
end

