# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Currencies do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Currencies"
  ]

  @type t :: %__MODULE__{
    :"Currencies" => [XeroAccountingAPI.Model.Currency.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Currencies do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Currencies", :list, XeroAccountingAPI.Model.Currency, options)
  end
end

