# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Currency do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Code",
    :"Description"
  ]

  @type t :: %__MODULE__{
    :"Code" => XeroAccountingAPI.Model.CurrencyCode.t | nil,
    :"Description" => String.t | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Currency do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Code", :struct, XeroAccountingAPI.Model.CurrencyCode, options)
  end
end

