# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Element do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ValidationErrors",
    :"BatchPaymentID",
    :"BankTransactionID",
    :"CreditNoteID",
    :"ContactID",
    :"InvoiceID",
    :"ItemID",
    :"PurchaseOrderID"
  ]

  @type t :: %__MODULE__{
    :"ValidationErrors" => [XeroAccountingAPI.Model.ValidationError.t] | nil,
    :"BatchPaymentID" => String.t | nil,
    :"BankTransactionID" => String.t | nil,
    :"CreditNoteID" => String.t | nil,
    :"ContactID" => String.t | nil,
    :"InvoiceID" => String.t | nil,
    :"ItemID" => String.t | nil,
    :"PurchaseOrderID" => String.t | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Element do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ValidationErrors", :list, XeroAccountingAPI.Model.ValidationError, options)
  end
end

