# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Employee do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"EmployeeID",
    :"Status",
    :"FirstName",
    :"LastName",
    :"ExternalLink",
    :"UpdatedDateUTC",
    :"StatusAttributeString",
    :"ValidationErrors"
  ]

  @type t :: %__MODULE__{
    :"EmployeeID" => String.t | nil,
    :"Status" => String.t | nil,
    :"FirstName" => String.t | nil,
    :"LastName" => String.t | nil,
    :"ExternalLink" => XeroAccountingAPI.Model.ExternalLink.t | nil,
    :"UpdatedDateUTC" => String.t | nil,
    :"StatusAttributeString" => String.t | nil,
    :"ValidationErrors" => [XeroAccountingAPI.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Employee do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ExternalLink", :struct, XeroAccountingAPI.Model.ExternalLink, options)
    |> deserialize(:"ValidationErrors", :list, XeroAccountingAPI.Model.ValidationError, options)
  end
end

