# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Employees do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Employees"
  ]

  @type t :: %__MODULE__{
    :"Employees" => [XeroAccountingAPI.Model.Employee.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Employees do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Employees", :list, XeroAccountingAPI.Model.Employee, options)
  end
end

