# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Error do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ErrorNumber",
    :"Type",
    :"Message",
    :"Elements"
  ]

  @type t :: %__MODULE__{
    :"ErrorNumber" => integer() | nil,
    :"Type" => String.t | nil,
    :"Message" => String.t | nil,
    :"Elements" => [XeroAccountingAPI.Model.Element.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Error do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Elements", :list, XeroAccountingAPI.Model.Element, options)
  end
end

