# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.ExpenseClaims do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ExpenseClaims"
  ]

  @type t :: %__MODULE__{
    :"ExpenseClaims" => [XeroAccountingAPI.Model.ExpenseClaim.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.ExpenseClaims do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ExpenseClaims", :list, XeroAccountingAPI.Model.ExpenseClaim, options)
  end
end

