# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.HistoryRecord do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Details",
    :"Changes",
    :"User",
    :"DateUTC"
  ]

  @type t :: %__MODULE__{
    :"Details" => String.t | nil,
    :"Changes" => String.t | nil,
    :"User" => String.t | nil,
    :"DateUTC" => String.t | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.HistoryRecord do
  def decode(value, _options) do
    value
  end
end

