# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.HistoryRecords do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"HistoryRecords"
  ]

  @type t :: %__MODULE__{
    :"HistoryRecords" => [XeroAccountingAPI.Model.HistoryRecord.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.HistoryRecords do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"HistoryRecords", :list, XeroAccountingAPI.Model.HistoryRecord, options)
  end
end

