# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.ImportSummaryObject do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ImportSummary"
  ]

  @type t :: %__MODULE__{
    :"ImportSummary" => XeroAccountingAPI.Model.ImportSummary.t | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.ImportSummaryObject do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ImportSummary", :struct, XeroAccountingAPI.Model.ImportSummary, options)
  end
end

