# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Invoices do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Invoices"
  ]

  @type t :: %__MODULE__{
    :"Invoices" => [XeroAccountingAPI.Model.Invoice.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Invoices do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Invoices", :list, XeroAccountingAPI.Model.Invoice, options)
  end
end

