# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.InvoiceReminders do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"InvoiceReminders"
  ]

  @type t :: %__MODULE__{
    :"InvoiceReminders" => [XeroAccountingAPI.Model.InvoiceReminder.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.InvoiceReminders do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"InvoiceReminders", :list, XeroAccountingAPI.Model.InvoiceReminder, options)
  end
end

