# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Items do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Items"
  ]

  @type t :: %__MODULE__{
    :"Items" => [XeroAccountingAPI.Model.Item.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Items do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Items", :list, XeroAccountingAPI.Model.Item, options)
  end
end

