# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Item do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Code",
    :"InventoryAssetAccountCode",
    :"Name",
    :"IsSold",
    :"IsPurchased",
    :"Description",
    :"PurchaseDescription",
    :"PurchaseDetails",
    :"SalesDetails",
    :"IsTrackedAsInventory",
    :"TotalCostPool",
    :"QuantityOnHand",
    :"UpdatedDateUTC",
    :"ItemID",
    :"StatusAttributeString",
    :"ValidationErrors"
  ]

  @type t :: %__MODULE__{
    :"Code" => String.t,
    :"InventoryAssetAccountCode" => String.t | nil,
    :"Name" => String.t | nil,
    :"IsSold" => boolean() | nil,
    :"IsPurchased" => boolean() | nil,
    :"Description" => String.t | nil,
    :"PurchaseDescription" => String.t | nil,
    :"PurchaseDetails" => XeroAccountingAPI.Model.Purchase.t | nil,
    :"SalesDetails" => XeroAccountingAPI.Model.Purchase.t | nil,
    :"IsTrackedAsInventory" => boolean() | nil,
    :"TotalCostPool" => float() | nil,
    :"QuantityOnHand" => float() | nil,
    :"UpdatedDateUTC" => String.t | nil,
    :"ItemID" => String.t | nil,
    :"StatusAttributeString" => String.t | nil,
    :"ValidationErrors" => [XeroAccountingAPI.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Item do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"PurchaseDetails", :struct, XeroAccountingAPI.Model.Purchase, options)
    |> deserialize(:"SalesDetails", :struct, XeroAccountingAPI.Model.Purchase, options)
    |> deserialize(:"ValidationErrors", :list, XeroAccountingAPI.Model.ValidationError, options)
  end
end

