# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Journals do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Journals"
  ]

  @type t :: %__MODULE__{
    :"Journals" => [XeroAccountingAPI.Model.Journal.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Journals do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Journals", :list, XeroAccountingAPI.Model.Journal, options)
  end
end

