# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Journal do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"JournalID",
    :"JournalDate",
    :"JournalNumber",
    :"CreatedDateUTC",
    :"Reference",
    :"SourceID",
    :"SourceType",
    :"JournalLines"
  ]

  @type t :: %__MODULE__{
    :"JournalID" => String.t | nil,
    :"JournalDate" => String.t | nil,
    :"JournalNumber" => integer() | nil,
    :"CreatedDateUTC" => String.t | nil,
    :"Reference" => String.t | nil,
    :"SourceID" => String.t | nil,
    :"SourceType" => String.t | nil,
    :"JournalLines" => [XeroAccountingAPI.Model.JournalLine.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Journal do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"JournalLines", :list, XeroAccountingAPI.Model.JournalLine, options)
  end
end

