# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.LinkedTransaction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"SourceTransactionID",
    :"SourceLineItemID",
    :"ContactID",
    :"TargetTransactionID",
    :"TargetLineItemID",
    :"LinkedTransactionID",
    :"Status",
    :"Type",
    :"UpdatedDateUTC",
    :"SourceTransactionTypeCode",
    :"ValidationErrors"
  ]

  @type t :: %__MODULE__{
    :"SourceTransactionID" => String.t | nil,
    :"SourceLineItemID" => String.t | nil,
    :"ContactID" => String.t | nil,
    :"TargetTransactionID" => String.t | nil,
    :"TargetLineItemID" => String.t | nil,
    :"LinkedTransactionID" => String.t | nil,
    :"Status" => String.t | nil,
    :"Type" => String.t | nil,
    :"UpdatedDateUTC" => String.t | nil,
    :"SourceTransactionTypeCode" => String.t | nil,
    :"ValidationErrors" => [XeroAccountingAPI.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.LinkedTransaction do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ValidationErrors", :list, XeroAccountingAPI.Model.ValidationError, options)
  end
end

