# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.LinkedTransactions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"LinkedTransactions"
  ]

  @type t :: %__MODULE__{
    :"LinkedTransactions" => [XeroAccountingAPI.Model.LinkedTransaction.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.LinkedTransactions do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"LinkedTransactions", :list, XeroAccountingAPI.Model.LinkedTransaction, options)
  end
end

