# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.ManualJournals do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ManualJournals"
  ]

  @type t :: %__MODULE__{
    :"ManualJournals" => [XeroAccountingAPI.Model.ManualJournal.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.ManualJournals do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ManualJournals", :list, XeroAccountingAPI.Model.ManualJournal, options)
  end
end

