# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.OnlineInvoices do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"OnlineInvoices"
  ]

  @type t :: %__MODULE__{
    :"OnlineInvoices" => [XeroAccountingAPI.Model.OnlineInvoice.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.OnlineInvoices do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"OnlineInvoices", :list, XeroAccountingAPI.Model.OnlineInvoice, options)
  end
end

