# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Overpayments do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Overpayments"
  ]

  @type t :: %__MODULE__{
    :"Overpayments" => [XeroAccountingAPI.Model.Overpayment.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Overpayments do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Overpayments", :list, XeroAccountingAPI.Model.Overpayment, options)
  end
end

