# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.PaymentService do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"PaymentServiceID",
    :"PaymentServiceName",
    :"PaymentServiceUrl",
    :"PayNowText",
    :"PaymentServiceType",
    :"ValidationErrors"
  ]

  @type t :: %__MODULE__{
    :"PaymentServiceID" => String.t | nil,
    :"PaymentServiceName" => String.t | nil,
    :"PaymentServiceUrl" => String.t | nil,
    :"PayNowText" => String.t | nil,
    :"PaymentServiceType" => String.t | nil,
    :"ValidationErrors" => [XeroAccountingAPI.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.PaymentService do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ValidationErrors", :list, XeroAccountingAPI.Model.ValidationError, options)
  end
end

