# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.PaymentDelete do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Status"
  ]

  @type t :: %__MODULE__{
    :"Status" => String.t
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.PaymentDelete do
  def decode(value, _options) do
    value
  end
end

