# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Payments do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Payments"
  ]

  @type t :: %__MODULE__{
    :"Payments" => [XeroAccountingAPI.Model.Payment.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Payments do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Payments", :list, XeroAccountingAPI.Model.Payment, options)
  end
end

