# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.PaymentTerm do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Bills",
    :"Sales"
  ]

  @type t :: %__MODULE__{
    :"Bills" => XeroAccountingAPI.Model.Bill.t | nil,
    :"Sales" => XeroAccountingAPI.Model.Bill.t | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.PaymentTerm do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Bills", :struct, XeroAccountingAPI.Model.Bill, options)
    |> deserialize(:"Sales", :struct, XeroAccountingAPI.Model.Bill, options)
  end
end

