# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Prepayments do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Prepayments"
  ]

  @type t :: %__MODULE__{
    :"Prepayments" => [XeroAccountingAPI.Model.Prepayment.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Prepayments do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Prepayments", :list, XeroAccountingAPI.Model.Prepayment, options)
  end
end

