# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.PurchaseOrder do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Contact",
    :"LineItems",
    :"Date",
    :"DeliveryDate",
    :"LineAmountTypes",
    :"PurchaseOrderNumber",
    :"Reference",
    :"BrandingThemeID",
    :"CurrencyCode",
    :"Status",
    :"SentToContact",
    :"DeliveryAddress",
    :"AttentionTo",
    :"Telephone",
    :"DeliveryInstructions",
    :"ExpectedArrivalDate",
    :"PurchaseOrderID",
    :"CurrencyRate",
    :"SubTotal",
    :"TotalTax",
    :"Total",
    :"TotalDiscount",
    :"HasAttachments",
    :"UpdatedDateUTC",
    :"StatusAttributeString",
    :"ValidationErrors",
    :"Warnings",
    :"Attachments"
  ]

  @type t :: %__MODULE__{
    :"Contact" => XeroAccountingAPI.Model.Contact.t | nil,
    :"LineItems" => [XeroAccountingAPI.Model.LineItem.t] | nil,
    :"Date" => String.t | nil,
    :"DeliveryDate" => String.t | nil,
    :"LineAmountTypes" => XeroAccountingAPI.Model.LineAmountTypes.t | nil,
    :"PurchaseOrderNumber" => String.t | nil,
    :"Reference" => String.t | nil,
    :"BrandingThemeID" => String.t | nil,
    :"CurrencyCode" => XeroAccountingAPI.Model.CurrencyCode.t | nil,
    :"Status" => String.t | nil,
    :"SentToContact" => boolean() | nil,
    :"DeliveryAddress" => String.t | nil,
    :"AttentionTo" => String.t | nil,
    :"Telephone" => String.t | nil,
    :"DeliveryInstructions" => String.t | nil,
    :"ExpectedArrivalDate" => String.t | nil,
    :"PurchaseOrderID" => String.t | nil,
    :"CurrencyRate" => float() | nil,
    :"SubTotal" => float() | nil,
    :"TotalTax" => float() | nil,
    :"Total" => float() | nil,
    :"TotalDiscount" => float() | nil,
    :"HasAttachments" => boolean() | nil,
    :"UpdatedDateUTC" => String.t | nil,
    :"StatusAttributeString" => String.t | nil,
    :"ValidationErrors" => [XeroAccountingAPI.Model.ValidationError.t] | nil,
    :"Warnings" => [XeroAccountingAPI.Model.ValidationError.t] | nil,
    :"Attachments" => [XeroAccountingAPI.Model.Attachment.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.PurchaseOrder do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Contact", :struct, XeroAccountingAPI.Model.Contact, options)
    |> deserialize(:"LineItems", :list, XeroAccountingAPI.Model.LineItem, options)
    |> deserialize(:"LineAmountTypes", :struct, XeroAccountingAPI.Model.LineAmountTypes, options)
    |> deserialize(:"CurrencyCode", :struct, XeroAccountingAPI.Model.CurrencyCode, options)
    |> deserialize(:"ValidationErrors", :list, XeroAccountingAPI.Model.ValidationError, options)
    |> deserialize(:"Warnings", :list, XeroAccountingAPI.Model.ValidationError, options)
    |> deserialize(:"Attachments", :list, XeroAccountingAPI.Model.Attachment, options)
  end
end

