# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.PurchaseOrders do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"PurchaseOrders"
  ]

  @type t :: %__MODULE__{
    :"PurchaseOrders" => [XeroAccountingAPI.Model.PurchaseOrder.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.PurchaseOrders do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"PurchaseOrders", :list, XeroAccountingAPI.Model.PurchaseOrder, options)
  end
end

