# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Quote do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"QuoteID",
    :"QuoteNumber",
    :"Reference",
    :"Terms",
    :"Contact",
    :"LineItems",
    :"Date",
    :"DateString",
    :"ExpiryDate",
    :"ExpiryDateString",
    :"Status",
    :"CurrencyCode",
    :"CurrencyRate",
    :"SubTotal",
    :"TotalTax",
    :"Total",
    :"TotalDiscount",
    :"Title",
    :"Summary",
    :"BrandingThemeID",
    :"UpdatedDateUTC",
    :"LineAmountTypes",
    :"StatusAttributeString",
    :"ValidationErrors"
  ]

  @type t :: %__MODULE__{
    :"QuoteID" => String.t | nil,
    :"QuoteNumber" => String.t | nil,
    :"Reference" => String.t | nil,
    :"Terms" => String.t | nil,
    :"Contact" => XeroAccountingAPI.Model.Contact.t | nil,
    :"LineItems" => [XeroAccountingAPI.Model.LineItem.t] | nil,
    :"Date" => String.t | nil,
    :"DateString" => String.t | nil,
    :"ExpiryDate" => String.t | nil,
    :"ExpiryDateString" => String.t | nil,
    :"Status" => XeroAccountingAPI.Model.QuoteStatusCodes.t | nil,
    :"CurrencyCode" => XeroAccountingAPI.Model.CurrencyCode.t | nil,
    :"CurrencyRate" => float() | nil,
    :"SubTotal" => float() | nil,
    :"TotalTax" => float() | nil,
    :"Total" => float() | nil,
    :"TotalDiscount" => float() | nil,
    :"Title" => String.t | nil,
    :"Summary" => String.t | nil,
    :"BrandingThemeID" => String.t | nil,
    :"UpdatedDateUTC" => String.t | nil,
    :"LineAmountTypes" => XeroAccountingAPI.Model.QuoteLineAmountTypes.t | nil,
    :"StatusAttributeString" => String.t | nil,
    :"ValidationErrors" => [XeroAccountingAPI.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Quote do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Contact", :struct, XeroAccountingAPI.Model.Contact, options)
    |> deserialize(:"LineItems", :list, XeroAccountingAPI.Model.LineItem, options)
    |> deserialize(:"Status", :struct, XeroAccountingAPI.Model.QuoteStatusCodes, options)
    |> deserialize(:"CurrencyCode", :struct, XeroAccountingAPI.Model.CurrencyCode, options)
    |> deserialize(:"LineAmountTypes", :struct, XeroAccountingAPI.Model.QuoteLineAmountTypes, options)
    |> deserialize(:"ValidationErrors", :list, XeroAccountingAPI.Model.ValidationError, options)
  end
end

