# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Quotes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Quotes"
  ]

  @type t :: %__MODULE__{
    :"Quotes" => [XeroAccountingAPI.Model.Quote.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Quotes do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Quotes", :list, XeroAccountingAPI.Model.Quote, options)
  end
end

