# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Receipts do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Receipts"
  ]

  @type t :: %__MODULE__{
    :"Receipts" => [XeroAccountingAPI.Model.Receipt.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Receipts do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Receipts", :list, XeroAccountingAPI.Model.Receipt, options)
  end
end

