# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.RepeatingInvoices do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"RepeatingInvoices"
  ]

  @type t :: %__MODULE__{
    :"RepeatingInvoices" => [XeroAccountingAPI.Model.RepeatingInvoice.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.RepeatingInvoices do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"RepeatingInvoices", :list, XeroAccountingAPI.Model.RepeatingInvoice, options)
  end
end

