# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.RepeatingInvoice do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Type",
    :"Contact",
    :"Schedule",
    :"LineItems",
    :"LineAmountTypes",
    :"Reference",
    :"BrandingThemeID",
    :"CurrencyCode",
    :"Status",
    :"SubTotal",
    :"TotalTax",
    :"Total",
    :"RepeatingInvoiceID",
    :"ID",
    :"HasAttachments",
    :"Attachments"
  ]

  @type t :: %__MODULE__{
    :"Type" => String.t | nil,
    :"Contact" => XeroAccountingAPI.Model.Contact.t | nil,
    :"Schedule" => XeroAccountingAPI.Model.Schedule.t | nil,
    :"LineItems" => [XeroAccountingAPI.Model.LineItem.t] | nil,
    :"LineAmountTypes" => XeroAccountingAPI.Model.LineAmountTypes.t | nil,
    :"Reference" => String.t | nil,
    :"BrandingThemeID" => String.t | nil,
    :"CurrencyCode" => XeroAccountingAPI.Model.CurrencyCode.t | nil,
    :"Status" => String.t | nil,
    :"SubTotal" => float() | nil,
    :"TotalTax" => float() | nil,
    :"Total" => float() | nil,
    :"RepeatingInvoiceID" => String.t | nil,
    :"ID" => String.t | nil,
    :"HasAttachments" => boolean() | nil,
    :"Attachments" => [XeroAccountingAPI.Model.Attachment.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.RepeatingInvoice do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Contact", :struct, XeroAccountingAPI.Model.Contact, options)
    |> deserialize(:"Schedule", :struct, XeroAccountingAPI.Model.Schedule, options)
    |> deserialize(:"LineItems", :list, XeroAccountingAPI.Model.LineItem, options)
    |> deserialize(:"LineAmountTypes", :struct, XeroAccountingAPI.Model.LineAmountTypes, options)
    |> deserialize(:"CurrencyCode", :struct, XeroAccountingAPI.Model.CurrencyCode, options)
    |> deserialize(:"Attachments", :list, XeroAccountingAPI.Model.Attachment, options)
  end
end

