# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.ReportRows do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"RowType",
    :"Title",
    :"Cells",
    :"Rows"
  ]

  @type t :: %__MODULE__{
    :"RowType" => XeroAccountingAPI.Model.RowType.t | nil,
    :"Title" => String.t | nil,
    :"Cells" => [XeroAccountingAPI.Model.ReportCell.t] | nil,
    :"Rows" => [XeroAccountingAPI.Model.ReportRow.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.ReportRows do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"RowType", :struct, XeroAccountingAPI.Model.RowType, options)
    |> deserialize(:"Cells", :list, XeroAccountingAPI.Model.ReportCell, options)
    |> deserialize(:"Rows", :list, XeroAccountingAPI.Model.ReportRow, options)
  end
end

