# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.ReportCell do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Value",
    :"Attributes"
  ]

  @type t :: %__MODULE__{
    :"Value" => String.t | nil,
    :"Attributes" => [XeroAccountingAPI.Model.ReportAttribute.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.ReportCell do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Attributes", :list, XeroAccountingAPI.Model.ReportAttribute, options)
  end
end

