# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Report do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ReportName",
    :"ReportType",
    :"ReportTitle",
    :"ReportDate",
    :"UpdatedDateUTC",
    :"Contacts"
  ]

  @type t :: %__MODULE__{
    :"ReportName" => String.t | nil,
    :"ReportType" => String.t | nil,
    :"ReportTitle" => String.t | nil,
    :"ReportDate" => String.t | nil,
    :"UpdatedDateUTC" => String.t | nil,
    :"Contacts" => [XeroAccountingAPI.Model.TenNinetyNineContact.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Report do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Contacts", :list, XeroAccountingAPI.Model.TenNinetyNineContact, options)
  end
end

