# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.ReportWithRows do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Reports"
  ]

  @type t :: %__MODULE__{
    :"Reports" => [XeroAccountingAPI.Model.ReportWithRow.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.ReportWithRows do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Reports", :list, XeroAccountingAPI.Model.ReportWithRow, options)
  end
end

