# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Schedule do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Period",
    :"Unit",
    :"DueDate",
    :"DueDateType",
    :"StartDate",
    :"NextScheduledDate",
    :"EndDate"
  ]

  @type t :: %__MODULE__{
    :"Period" => integer() | nil,
    :"Unit" => String.t | nil,
    :"DueDate" => integer() | nil,
    :"DueDateType" => String.t | nil,
    :"StartDate" => String.t | nil,
    :"NextScheduledDate" => String.t | nil,
    :"EndDate" => String.t | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Schedule do
  def decode(value, _options) do
    value
  end
end

