# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Setup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ConversionDate",
    :"ConversionBalances",
    :"Accounts"
  ]

  @type t :: %__MODULE__{
    :"ConversionDate" => XeroAccountingAPI.Model.ConversionDate.t | nil,
    :"ConversionBalances" => [XeroAccountingAPI.Model.ConversionBalances.t] | nil,
    :"Accounts" => [XeroAccountingAPI.Model.Account.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Setup do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ConversionDate", :struct, XeroAccountingAPI.Model.ConversionDate, options)
    |> deserialize(:"ConversionBalances", :list, XeroAccountingAPI.Model.ConversionBalances, options)
    |> deserialize(:"Accounts", :list, XeroAccountingAPI.Model.Account, options)
  end
end

