# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.TaxRates do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"TaxRates"
  ]

  @type t :: %__MODULE__{
    :"TaxRates" => [XeroAccountingAPI.Model.TaxRate.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.TaxRates do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"TaxRates", :list, XeroAccountingAPI.Model.TaxRate, options)
  end
end

