# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.TenNinetyNineContact do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Box1",
    :"Box2",
    :"Box3",
    :"Box4",
    :"Box5",
    :"Box6",
    :"Box7",
    :"Box8",
    :"Box9",
    :"Box10",
    :"Box11",
    :"Box13",
    :"Box14",
    :"Name",
    :"FederalTaxIDType",
    :"City",
    :"Zip",
    :"State",
    :"Email",
    :"StreetAddress",
    :"TaxID",
    :"ContactId"
  ]

  @type t :: %__MODULE__{
    :"Box1" => float() | nil,
    :"Box2" => float() | nil,
    :"Box3" => float() | nil,
    :"Box4" => float() | nil,
    :"Box5" => float() | nil,
    :"Box6" => float() | nil,
    :"Box7" => float() | nil,
    :"Box8" => float() | nil,
    :"Box9" => float() | nil,
    :"Box10" => float() | nil,
    :"Box11" => float() | nil,
    :"Box13" => float() | nil,
    :"Box14" => float() | nil,
    :"Name" => String.t | nil,
    :"FederalTaxIDType" => String.t | nil,
    :"City" => String.t | nil,
    :"Zip" => String.t | nil,
    :"State" => String.t | nil,
    :"Email" => String.t | nil,
    :"StreetAddress" => String.t | nil,
    :"TaxID" => String.t | nil,
    :"ContactId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.TenNinetyNineContact do
  def decode(value, _options) do
    value
  end
end

