# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.TrackingCategories do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"TrackingCategories"
  ]

  @type t :: %__MODULE__{
    :"TrackingCategories" => [XeroAccountingAPI.Model.TrackingCategory.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.TrackingCategories do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"TrackingCategories", :list, XeroAccountingAPI.Model.TrackingCategory, options)
  end
end

