# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.TrackingOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Options"
  ]

  @type t :: %__MODULE__{
    :"Options" => [XeroAccountingAPI.Model.TrackingOption.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.TrackingOptions do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Options", :list, XeroAccountingAPI.Model.TrackingOption, options)
  end
end

