# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.TrackingCategory do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"TrackingCategoryID",
    :"TrackingOptionID",
    :"Name",
    :"Option",
    :"Status",
    :"Options"
  ]

  @type t :: %__MODULE__{
    :"TrackingCategoryID" => String.t | nil,
    :"TrackingOptionID" => String.t | nil,
    :"Name" => String.t | nil,
    :"Option" => String.t | nil,
    :"Status" => String.t | nil,
    :"Options" => [XeroAccountingAPI.Model.TrackingOption.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.TrackingCategory do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Options", :list, XeroAccountingAPI.Model.TrackingOption, options)
  end
end

