# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.Users do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Users"
  ]

  @type t :: %__MODULE__{
    :"Users" => [XeroAccountingAPI.Model.User.t] | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.Users do
  import XeroAccountingAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Users", :list, XeroAccountingAPI.Model.User, options)
  end
end

