# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Model.User do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"UserID",
    :"EmailAddress",
    :"FirstName",
    :"LastName",
    :"UpdatedDateUTC",
    :"IsSubscriber",
    :"OrganisationRole"
  ]

  @type t :: %__MODULE__{
    :"UserID" => String.t | nil,
    :"EmailAddress" => String.t | nil,
    :"FirstName" => String.t | nil,
    :"LastName" => String.t | nil,
    :"UpdatedDateUTC" => String.t | nil,
    :"IsSubscriber" => boolean() | nil,
    :"OrganisationRole" => String.t | nil
  }
end

defimpl Poison.Decoder, for: XeroAccountingAPI.Model.User do
  def decode(value, _options) do
    value
  end
end

