# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Accounts do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Accounts
  ]

  @type t :: %__MODULE__{
          :Accounts => [Xero.Model.Account.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Accounts do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Accounts, :list, Xero.Model.Account, options)
  end
end
