# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Actions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Actions
  ]

  @type t :: %__MODULE__{
          :Actions => [Xero.Model.Action.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Actions do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Actions, :list, Xero.Model.Action, options)
  end
end
