# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Allocation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Invoice,
    :Overpayment,
    :Prepayment,
    :CreditNote,
    :Amount,
    :Date,
    :StatusAttributeString,
    :ValidationErrors
  ]

  @type t :: %__MODULE__{
          :Invoice => Xero.Model.Invoice.t(),
          :Overpayment => Xero.Model.Overpayment.t() | nil,
          :Prepayment => Xero.Model.Prepayment.t() | nil,
          :CreditNote => Xero.Model.CreditNote.t() | nil,
          :Amount => float(),
          :Date => String.t(),
          :StatusAttributeString => String.t() | nil,
          :ValidationErrors => [Xero.Model.ValidationError.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Allocation do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Invoice, :struct, Xero.Model.Invoice, options)
    |> deserialize(:Overpayment, :struct, Xero.Model.Overpayment, options)
    |> deserialize(:Prepayment, :struct, Xero.Model.Prepayment, options)
    |> deserialize(:CreditNote, :struct, Xero.Model.CreditNote, options)
    |> deserialize(:ValidationErrors, :list, Xero.Model.ValidationError, options)
  end
end
