# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Allocations do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Allocations
  ]

  @type t :: %__MODULE__{
          :Allocations => [Xero.Model.Allocation.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Allocations do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Allocations, :list, Xero.Model.Allocation, options)
  end
end
