# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Attachment do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :AttachmentID,
    :FileName,
    :Url,
    :MimeType,
    :ContentLength,
    :IncludeOnline
  ]

  @type t :: %__MODULE__{
          :AttachmentID => String.t() | nil,
          :FileName => String.t() | nil,
          :Url => String.t() | nil,
          :MimeType => String.t() | nil,
          :ContentLength => integer() | nil,
          :IncludeOnline => boolean() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Attachment do
  def decode(value, _options) do
    value
  end
end
