# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Attachments do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Attachments
  ]

  @type t :: %__MODULE__{
          :Attachments => [Xero.Model.Attachment.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Attachments do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Attachments, :list, Xero.Model.Attachment, options)
  end
end
