# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Balances do
  @moduledoc """
  The raw AccountsReceivable(sales invoices) and AccountsPayable(bills) outstanding and overdue amounts, not converted to base currency (read only)
  """

  @derive [Poison.Encoder]
  defstruct [
    :AccountsReceivable,
    :AccountsPayable
  ]

  @type t :: %__MODULE__{
          :AccountsReceivable => Xero.Model.AccountsReceivable.t() | nil,
          :AccountsPayable => Xero.Model.AccountsPayable.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Balances do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:AccountsReceivable, :struct, Xero.Model.AccountsReceivable, options)
    |> deserialize(:AccountsPayable, :struct, Xero.Model.AccountsPayable, options)
  end
end
