# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.BankTransfers do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :BankTransfers
  ]

  @type t :: %__MODULE__{
          :BankTransfers => [Xero.Model.BankTransfer.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.BankTransfers do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:BankTransfers, :list, Xero.Model.BankTransfer, options)
  end
end
