# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.BankTransaction do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Contact,
    :LineItems,
    :BankAccount,
    :IsReconciled,
    :Date,
    :Reference,
    :CurrencyCode,
    :CurrencyRate,
    :Url,
    :Status,
    :LineAmountTypes,
    :SubTotal,
    :TotalTax,
    :Total,
    :BankTransactionID,
    :PrepaymentID,
    :OverpaymentID,
    :UpdatedDateUTC,
    :HasAttachments,
    :StatusAttributeString,
    :ValidationErrors
  ]

  @type t :: %__MODULE__{
          :Type => String.t(),
          :Contact => Xero.Model.Contact.t() | nil,
          :LineItems => [Xero.Model.LineItem.t()],
          :BankAccount => Xero.Model.Account.t(),
          :IsReconciled => boolean() | nil,
          :Date => String.t() | nil,
          :Reference => String.t() | nil,
          :CurrencyCode => Xero.Model.CurrencyCode.t() | nil,
          :CurrencyRate => float() | nil,
          :Url => String.t() | nil,
          :Status => String.t() | nil,
          :LineAmountTypes => Xero.Model.LineAmountTypes.t() | nil,
          :SubTotal => float() | nil,
          :TotalTax => float() | nil,
          :Total => float() | nil,
          :BankTransactionID => String.t() | nil,
          :PrepaymentID => String.t() | nil,
          :OverpaymentID => String.t() | nil,
          :UpdatedDateUTC => String.t() | nil,
          :HasAttachments => boolean() | nil,
          :StatusAttributeString => String.t() | nil,
          :ValidationErrors => [Xero.Model.ValidationError.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.BankTransaction do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Contact, :struct, Xero.Model.Contact, options)
    |> deserialize(:LineItems, :list, Xero.Model.LineItem, options)
    |> deserialize(:BankAccount, :struct, Xero.Model.Account, options)
    |> deserialize(:CurrencyCode, :struct, Xero.Model.CurrencyCode, options)
    |> deserialize(:LineAmountTypes, :struct, Xero.Model.LineAmountTypes, options)
    |> deserialize(:ValidationErrors, :list, Xero.Model.ValidationError, options)
  end
end
