# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.BrandingTheme do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :BrandingThemeID,
    :Name,
    :LogoUrl,
    :Type,
    :SortOrder,
    :CreatedDateUTC
  ]

  @type t :: %__MODULE__{
          :BrandingThemeID => String.t() | nil,
          :Name => String.t() | nil,
          :LogoUrl => String.t() | nil,
          :Type => String.t() | nil,
          :SortOrder => integer() | nil,
          :CreatedDateUTC => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.BrandingTheme do
  def decode(value, _options) do
    value
  end
end
