# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.BudgetBalance do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Period,
    :Amount,
    :UnitAmount,
    :Notes
  ]

  @type t :: %__MODULE__{
          :Period => String.t() | nil,
          :Amount => float() | nil,
          :UnitAmount => float() | nil,
          :Notes => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.BudgetBalance do
  def decode(value, _options) do
    value
  end
end
