# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Budgets do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Budgets
  ]

  @type t :: %__MODULE__{
          :Budgets => [Xero.Model.Budget.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Budgets do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Budgets, :list, Xero.Model.Budget, options)
  end
end
