# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ContactGroup do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Status,
    :ContactGroupID,
    :Contacts
  ]

  @type t :: %__MODULE__{
          :Name => String.t() | nil,
          :Status => String.t() | nil,
          :ContactGroupID => String.t() | nil,
          :Contacts => [Xero.Model.Contact.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ContactGroup do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Contacts, :list, Xero.Model.Contact, options)
  end
end
