# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ContactPerson do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :FirstName,
    :LastName,
    :EmailAddress,
    :IncludeInEmails
  ]

  @type t :: %__MODULE__{
          :FirstName => String.t() | nil,
          :LastName => String.t() | nil,
          :EmailAddress => String.t() | nil,
          :IncludeInEmails => boolean() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ContactPerson do
  def decode(value, _options) do
    value
  end
end
