# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Contacts do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Contacts
  ]

  @type t :: %__MODULE__{
          :Contacts => [Xero.Model.Contact.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Contacts do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Contacts, :list, Xero.Model.Contact, options)
  end
end
