# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ConversionBalances do
  @moduledoc """
  Balance supplied for each account that has a value as at the conversion date.
  """

  @derive [Poison.Encoder]
  defstruct [
    :AccountCode,
    :Balance,
    :BalanceDetails
  ]

  @type t :: %__MODULE__{
          :AccountCode => String.t() | nil,
          :Balance => float() | nil,
          :BalanceDetails => [Xero.Model.BalanceDetails.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ConversionBalances do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:BalanceDetails, :list, Xero.Model.BalanceDetails, options)
  end
end
