# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.CreditNotes do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CreditNotes
  ]

  @type t :: %__MODULE__{
          :CreditNotes => [Xero.Model.CreditNote.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.CreditNotes do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:CreditNotes, :list, Xero.Model.CreditNote, options)
  end
end
