# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Currencies do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Currencies
  ]

  @type t :: %__MODULE__{
          :Currencies => [Xero.Model.Currency.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Currencies do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Currencies, :list, Xero.Model.Currency, options)
  end
end
