# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Currency do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Code,
    :Description
  ]

  @type t :: %__MODULE__{
          :Code => Xero.Model.CurrencyCode.t() | nil,
          :Description => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Currency do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Code, :struct, Xero.Model.CurrencyCode, options)
  end
end
