# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Employee do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :EmployeeID,
    :Status,
    :FirstName,
    :LastName,
    :ExternalLink,
    :UpdatedDateUTC,
    :StatusAttributeString,
    :ValidationErrors
  ]

  @type t :: %__MODULE__{
          :EmployeeID => String.t() | nil,
          :Status => String.t() | nil,
          :FirstName => String.t() | nil,
          :LastName => String.t() | nil,
          :ExternalLink => Xero.Model.ExternalLink.t() | nil,
          :UpdatedDateUTC => String.t() | nil,
          :StatusAttributeString => String.t() | nil,
          :ValidationErrors => [Xero.Model.ValidationError.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Employee do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:ExternalLink, :struct, Xero.Model.ExternalLink, options)
    |> deserialize(:ValidationErrors, :list, Xero.Model.ValidationError, options)
  end
end
