# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.HistoryRecords do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :HistoryRecords
  ]

  @type t :: %__MODULE__{
          :HistoryRecords => [Xero.Model.HistoryRecord.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.HistoryRecords do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:HistoryRecords, :list, Xero.Model.HistoryRecord, options)
  end
end
