# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ImportSummary do
  @moduledoc """
  A summary of the import from setup endpoint
  """

  @derive [Poison.Encoder]
  defstruct [
    :Accounts,
    :Organisation
  ]

  @type t :: %__MODULE__{
          :Accounts => Xero.Model.ImportSummaryAccounts.t() | nil,
          :Organisation => Xero.Model.ImportSummaryOrganisation.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ImportSummary do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Accounts, :struct, Xero.Model.ImportSummaryAccounts, options)
    |> deserialize(:Organisation, :struct, Xero.Model.ImportSummaryOrganisation, options)
  end
end
