# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ImportSummaryOrganisation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Present
  ]

  @type t :: %__MODULE__{
          :Present => boolean() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ImportSummaryOrganisation do
  def decode(value, _options) do
    value
  end
end
