# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ImportSummaryObject do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ImportSummary
  ]

  @type t :: %__MODULE__{
          :ImportSummary => Xero.Model.ImportSummary.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ImportSummaryObject do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:ImportSummary, :struct, Xero.Model.ImportSummary, options)
  end
end
