# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ImportSummaryAccounts do
  @moduledoc """
  A summary of the accounts changes
  """

  @derive [Poison.Encoder]
  defstruct [
    :Total,
    :New,
    :Updated,
    :Deleted,
    :Locked,
    :System,
    :Errored,
    :Present,
    :NewOrUpdated
  ]

  @type t :: %__MODULE__{
          :Total => integer() | nil,
          :New => integer() | nil,
          :Updated => integer() | nil,
          :Deleted => integer() | nil,
          :Locked => integer() | nil,
          :System => integer() | nil,
          :Errored => integer() | nil,
          :Present => boolean() | nil,
          :NewOrUpdated => integer() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ImportSummaryAccounts do
  def decode(value, _options) do
    value
  end
end
