# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Invoices do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Invoices
  ]

  @type t :: %__MODULE__{
          :Invoices => [Xero.Model.Invoice.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Invoices do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Invoices, :list, Xero.Model.Invoice, options)
  end
end
