# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Items do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Items
  ]

  @type t :: %__MODULE__{
          :Items => [Xero.Model.Item.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Items do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Items, :list, Xero.Model.Item, options)
  end
end
