# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Journals do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Journals
  ]

  @type t :: %__MODULE__{
          :Journals => [Xero.Model.Journal.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Journals do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Journals, :list, Xero.Model.Journal, options)
  end
end
