# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.LineItemTracking do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :TrackingCategoryID,
    :TrackingOptionID,
    :Name,
    :Option
  ]

  @type t :: %__MODULE__{
          :TrackingCategoryID => String.t() | nil,
          :TrackingOptionID => String.t() | nil,
          :Name => String.t() | nil,
          :Option => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.LineItemTracking do
  def decode(value, _options) do
    value
  end
end
