# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.LineItem do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :LineItemID,
    :Description,
    :Quantity,
    :UnitAmount,
    :ItemCode,
    :AccountCode,
    :AccountID,
    :TaxType,
    :TaxAmount,
    :LineAmount,
    :Tracking,
    :DiscountRate,
    :DiscountAmount,
    :RepeatingInvoiceID
  ]

  @type t :: %__MODULE__{
          :LineItemID => String.t() | nil,
          :Description => String.t() | nil,
          :Quantity => float() | nil,
          :UnitAmount => float() | nil,
          :ItemCode => String.t() | nil,
          :AccountCode => String.t() | nil,
          :AccountID => String.t() | nil,
          :TaxType => String.t() | nil,
          :TaxAmount => float() | nil,
          :LineAmount => float() | nil,
          :Tracking => [Xero.Model.LineItemTracking.t()] | nil,
          :DiscountRate => float() | nil,
          :DiscountAmount => float() | nil,
          :RepeatingInvoiceID => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.LineItem do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Tracking, :list, Xero.Model.LineItemTracking, options)
  end
end
