# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.LinkedTransactions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :LinkedTransactions
  ]

  @type t :: %__MODULE__{
          :LinkedTransactions => [Xero.Model.LinkedTransaction.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.LinkedTransactions do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:LinkedTransactions, :list, Xero.Model.LinkedTransaction, options)
  end
end
