# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ManualJournals do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ManualJournals
  ]

  @type t :: %__MODULE__{
          :ManualJournals => [Xero.Model.ManualJournal.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ManualJournals do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:ManualJournals, :list, Xero.Model.ManualJournal, options)
  end
end
