# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ManualJournalLine do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :LineAmount,
    :AccountCode,
    :AccountID,
    :Description,
    :TaxType,
    :Tracking,
    :TaxAmount,
    :IsBlank
  ]

  @type t :: %__MODULE__{
          :LineAmount => float() | nil,
          :AccountCode => String.t() | nil,
          :AccountID => String.t() | nil,
          :Description => String.t() | nil,
          :TaxType => String.t() | nil,
          :Tracking => [Xero.Model.TrackingCategory.t()] | nil,
          :TaxAmount => float() | nil,
          :IsBlank => boolean() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ManualJournalLine do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Tracking, :list, Xero.Model.TrackingCategory, options)
  end
end
