# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.OnlineInvoices do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :OnlineInvoices
  ]

  @type t :: %__MODULE__{
          :OnlineInvoices => [Xero.Model.OnlineInvoice.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.OnlineInvoices do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:OnlineInvoices, :list, Xero.Model.OnlineInvoice, options)
  end
end
