# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Organisations do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Organisations
  ]

  @type t :: %__MODULE__{
          :Organisations => [Xero.Model.Organisation.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Organisations do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Organisations, :list, Xero.Model.Organisation, options)
  end
end
