# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.PaymentServices do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :PaymentServices
  ]

  @type t :: %__MODULE__{
          :PaymentServices => [Xero.Model.PaymentService.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.PaymentServices do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:PaymentServices, :list, Xero.Model.PaymentService, options)
  end
end
