# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.PaymentTerm do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Bills,
    :Sales
  ]

  @type t :: %__MODULE__{
          :Bills => Xero.Model.Bill.t() | nil,
          :Sales => Xero.Model.Bill.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.PaymentTerm do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Bills, :struct, Xero.Model.Bill, options)
    |> deserialize(:Sales, :struct, Xero.Model.Bill, options)
  end
end
