# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Prepayments do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Prepayments
  ]

  @type t :: %__MODULE__{
          :Prepayments => [Xero.Model.Prepayment.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Prepayments do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Prepayments, :list, Xero.Model.Prepayment, options)
  end
end
