# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Purchase do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :UnitPrice,
    :AccountCode,
    :COGSAccountCode,
    :TaxType
  ]

  @type t :: %__MODULE__{
          :UnitPrice => float() | nil,
          :AccountCode => String.t() | nil,
          :COGSAccountCode => String.t() | nil,
          :TaxType => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Purchase do
  def decode(value, _options) do
    value
  end
end
