# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.PurchaseOrders do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :PurchaseOrders
  ]

  @type t :: %__MODULE__{
          :PurchaseOrders => [Xero.Model.PurchaseOrder.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.PurchaseOrders do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:PurchaseOrders, :list, Xero.Model.PurchaseOrder, options)
  end
end
