# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Quotes do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Quotes
  ]

  @type t :: %__MODULE__{
          :Quotes => [Xero.Model.Quote.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Quotes do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Quotes, :list, Xero.Model.Quote, options)
  end
end
