# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Receipt do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Date,
    :Contact,
    :LineItems,
    :User,
    :Reference,
    :LineAmountTypes,
    :SubTotal,
    :TotalTax,
    :Total,
    :ReceiptID,
    :Status,
    :ReceiptNumber,
    :UpdatedDateUTC,
    :HasAttachments,
    :Url,
    :ValidationErrors,
    :Warnings,
    :Attachments
  ]

  @type t :: %__MODULE__{
          :Date => String.t() | nil,
          :Contact => Xero.Model.Contact.t() | nil,
          :LineItems => [Xero.Model.LineItem.t()] | nil,
          :User => Xero.Model.User.t() | nil,
          :Reference => String.t() | nil,
          :LineAmountTypes => Xero.Model.LineAmountTypes.t() | nil,
          :SubTotal => float() | nil,
          :TotalTax => float() | nil,
          :Total => float() | nil,
          :ReceiptID => String.t() | nil,
          :Status => String.t() | nil,
          :ReceiptNumber => String.t() | nil,
          :UpdatedDateUTC => String.t() | nil,
          :HasAttachments => boolean() | nil,
          :Url => String.t() | nil,
          :ValidationErrors => [Xero.Model.ValidationError.t()] | nil,
          :Warnings => [Xero.Model.ValidationError.t()] | nil,
          :Attachments => [Xero.Model.Attachment.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Receipt do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Contact, :struct, Xero.Model.Contact, options)
    |> deserialize(:LineItems, :list, Xero.Model.LineItem, options)
    |> deserialize(:User, :struct, Xero.Model.User, options)
    |> deserialize(:LineAmountTypes, :struct, Xero.Model.LineAmountTypes, options)
    |> deserialize(:ValidationErrors, :list, Xero.Model.ValidationError, options)
    |> deserialize(:Warnings, :list, Xero.Model.ValidationError, options)
    |> deserialize(:Attachments, :list, Xero.Model.Attachment, options)
  end
end
