# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Receipts do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Receipts
  ]

  @type t :: %__MODULE__{
          :Receipts => [Xero.Model.Receipt.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Receipts do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Receipts, :list, Xero.Model.Receipt, options)
  end
end
