# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.RepeatingInvoices do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :RepeatingInvoices
  ]

  @type t :: %__MODULE__{
          :RepeatingInvoices => [Xero.Model.RepeatingInvoice.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.RepeatingInvoices do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:RepeatingInvoices, :list, Xero.Model.RepeatingInvoice, options)
  end
end
