# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ReportCell do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Value,
    :Attributes
  ]

  @type t :: %__MODULE__{
          :Value => String.t() | nil,
          :Attributes => [Xero.Model.ReportAttribute.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ReportCell do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Attributes, :list, Xero.Model.ReportAttribute, options)
  end
end
