# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ReportFields do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :FieldID,
    :Description,
    :Value
  ]

  @type t :: %__MODULE__{
          :FieldID => String.t() | nil,
          :Description => String.t() | nil,
          :Value => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ReportFields do
  def decode(value, _options) do
    value
  end
end
