# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ReportRow do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :RowType,
    :Title,
    :Cells
  ]

  @type t :: %__MODULE__{
          :RowType => Xero.Model.RowType.t() | nil,
          :Title => String.t() | nil,
          :Cells => [Xero.Model.ReportCell.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ReportRow do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:RowType, :struct, Xero.Model.RowType, options)
    |> deserialize(:Cells, :list, Xero.Model.ReportCell, options)
  end
end
