# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ReportAttribute do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Id,
    :Value
  ]

  @type t :: %__MODULE__{
          :Id => String.t() | nil,
          :Value => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ReportAttribute do
  def decode(value, _options) do
    value
  end
end
