# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.RequestEmpty do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Status
  ]

  @type t :: %__MODULE__{
          :Status => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.RequestEmpty do
  def decode(value, _options) do
    value
  end
end
