# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.SalesTrackingCategory do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :TrackingCategoryName,
    :TrackingOptionName
  ]

  @type t :: %__MODULE__{
          :TrackingCategoryName => String.t() | nil,
          :TrackingOptionName => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.SalesTrackingCategory do
  def decode(value, _options) do
    value
  end
end
