# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.TaxRates do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :TaxRates
  ]

  @type t :: %__MODULE__{
          :TaxRates => [Xero.Model.TaxRate.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.TaxRates do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:TaxRates, :list, Xero.Model.TaxRate, options)
  end
end
