# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.TrackingOption do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :TrackingOptionID,
    :Name,
    :Status,
    :TrackingCategoryID
  ]

  @type t :: %__MODULE__{
          :TrackingOptionID => String.t() | nil,
          :Name => String.t() | nil,
          :Status => String.t() | nil,
          :TrackingCategoryID => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.TrackingOption do
  def decode(value, _options) do
    value
  end
end
