# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.TrackingOptions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Options
  ]

  @type t :: %__MODULE__{
          :Options => [Xero.Model.TrackingOption.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.TrackingOptions do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Options, :list, Xero.Model.TrackingOption, options)
  end
end
