# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.TrackingCategories do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :TrackingCategories
  ]

  @type t :: %__MODULE__{
          :TrackingCategories => [Xero.Model.TrackingCategory.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.TrackingCategories do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:TrackingCategories, :list, Xero.Model.TrackingCategory, options)
  end
end
