# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.TrackingCategory do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :TrackingCategoryID,
    :TrackingOptionID,
    :Name,
    :Option,
    :Status,
    :Options
  ]

  @type t :: %__MODULE__{
          :TrackingCategoryID => String.t() | nil,
          :TrackingOptionID => String.t() | nil,
          :Name => String.t() | nil,
          :Option => String.t() | nil,
          :Status => String.t() | nil,
          :Options => [Xero.Model.TrackingOption.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.TrackingCategory do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Options, :list, Xero.Model.TrackingOption, options)
  end
end
