# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.Users do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Users
  ]

  @type t :: %__MODULE__{
          :Users => [Xero.Model.User.t()] | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.Users do
  import Xero.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Users, :list, Xero.Model.User, options)
  end
end
