# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Xero.Model.ValidationError do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Message
  ]

  @type t :: %__MODULE__{
          :Message => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Xero.Model.ValidationError do
  def decode(value, _options) do
    value
  end
end
