# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule XeroAccountingAPI.Connection do
  @moduledoc """
  Handle Tesla connections for XeroAccountingAPI.
  """

  use Tesla

  # Add any middleware here (authentication)
  plug Tesla.Middleware.BaseUrl, "https://api.xero.com/api.xro/2.0"
  plug Tesla.Middleware.Headers, [{"user-agent", "Elixir"}]
  plug Tesla.Middleware.EncodeJson, engine: Poison

  @scopes [
    "email", # Grant read-only access to your email
    "openid", # Grant read-only access to your open id
    "profile", # your profile information
    "accounting.attachments", # Grant read-write access to attachments
    "accounting.attachments.read", # Grant read-only access to attachments
    "accounting.contacts", # Grant read-write access to contacts and contact groups
    "accounting.contacts.read", # Grant read-only access to contacts and contact groups
    "accounting.journals.read", # Grant read-only access to journals
    "accounting.reports.read", # Grant read-only access to accounting reports
    "accounting.reports.tenninetynine.read", # Grant read-only access to 1099 reports
    "accounting.settings", # Grant read-write access to organisation and account settings
    "accounting.settings.read", # Grant read-only access to organisation and account settings
    "accounting.transactions", # Grant read-write access to bank transactions, credit notes, invoices, repeating invoices
    "accounting.transactions.read", # Grant read-only access to invoices
    "paymentservices" # Grant read-write access to payment services
  ]

  @doc """
  Configure a client connection using a provided OAuth2 token as a Bearer token

  ## Parameters

  - token (String): Bearer token

  ## Returns

  Tesla.Env.client
  """
  @spec new(String.t) :: Tesla.Env.client
  def new(token) when is_binary(token) do
    Tesla.client([
      {Tesla.Middleware.Headers,  [{"authorization", "Bearer #{token}"}]}
    ])
  end

  @doc """
  Configure a client connection using a function which yields a Bearer token.

  ## Parameters

  - token_fetcher (function arity of 1): Callback which provides an OAuth2 token
    given a list of scopes

  ## Returns

  Tesla.Env.client
  """
  @spec new(((list(String.t)) -> String.t)) :: Tesla.Env.client
  def new(token_fetcher) when is_function(token_fetcher) do
    token_fetcher.(@scopes)
    |> new
  end
  @doc """
  Configure an authless client connection

  # Returns

  Tesla.Env.client
  """
  @spec new() :: Tesla.Env.client
  def new do
    Tesla.client([])
  end
end
